### ISSUE TITLE
Outside-in element missing

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#1]
![screenshot from 2016-10-03 16-59-33](https://cloud.githubusercontent.com/assets/3010324/19042290/b9e5e4f6-898b-11e6-8311-29a437817cd4.png)

**Comment by NemanjaTck** [comment]
Done

**Comment by NenadSC** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/18460472/19261621/c15cb374-8f92-11e6-9415-49768f57eee9.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261626/c6fd0932-8f92-11e6-9000-92bd5371f5da.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261646/de09d13c-8f92-11e6-9d38-25abf0fb5b14.png)
