### ISSUE TITLE
Fieldsets 

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#12]
![fieldsets](https://cloud.githubusercontent.com/assets/3010324/19146209/d96fe816-8bb2-11e6-900f-d7d9b9c4008a.png)
Issue derived from META Grouping issue. Providing screenshot for fieldsets, collapsed and normal.

**Comment by NemanjaTck** [comment]
Element finished.
![screen shot 2016-10-10 at 15 42 40](https://cloud.githubusercontent.com/assets/3010324/19238105/3f993da4-8f00-11e6-9a57-cbbb54a9d35d.png)

**Comment by NenadSC** [comment]
DONE

Collapse and expand symbols created and added to library.

![image](https://cloud.githubusercontent.com/assets/18460472/19261902/5dffcabc-8f94-11e6-9b91-910f7da04a02.png)
