### ISSUE TITLE
Vertical admin panel

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#13]
![adminbarvertical](https://cloud.githubusercontent.com/assets/3010324/19236434/b54c93ec-8ef7-11e6-8f0f-8a6e50cfc52f.png)
Need to add the element.

**Comment by NenadSC** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/18460472/19427589/3b5aa99a-9445-11e6-8f51-8692a16efd71.png)
