### ISSUE TITLE
Node right sidebar

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#18]
![noderightsidebar](https://cloud.githubusercontent.com/assets/3010324/19238914/f514df50-8f03-11e6-860c-ee83794dfb59.png)

**Comment by NemanjaTck** [comment]
When creating or editing content, sidebar on the right.

**Comment by NenadSC** [comment]
DONE

Collapse and expand symbols created and added to library.

![image](https://cloud.githubusercontent.com/assets/18460472/19261700/3c1e3b5a-8f93-11e6-90ef-365da35e11fd.png)

Expand states:

![image](https://cloud.githubusercontent.com/assets/18460472/19261706/41015f58-8f93-11e6-94bd-65ecf733b126.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261711/4b6df316-8f93-11e6-84e6-88953878dc67.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261716/51874b76-8f93-11e6-8953-7907ff3738c0.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261719/569c073c-8f93-11e6-8554-ef8d183b1bd0.png)

**Comment by NenadSC** [comment]
At the moment I don't see "COMMENT SETTINGS" part on our demo website, can you please enable that?

**Comment by NenadSC** [comment]
DONE

All sidebar elements and states are created, converted to symbols and grouped.

![image](https://cloud.githubusercontent.com/assets/18460472/19269629/edde44ac-8fbb-11e6-811a-f3171a5325b1.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19269591/bc88256c-8fbb-11e6-9994-07ac8417719c.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19269599/c3833334-8fbb-11e6-890c-84d8ca46d8fd.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19269610/d107a440-8fbb-11e6-8fb4-eb2ec1940a80.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19269619/d84b6bd8-8fbb-11e6-8006-f936a689ec4f.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19269621/dd850f14-8fbb-11e6-8330-f75e75e83cd1.png)

**Comment by NenadSC** [comment]
NOTE: Elements are now grouped only on symbols panel, there is no need to preview it in design page anymore (artboard) if we have it nicely sorted and aligned in symbols library.

![image](https://cloud.githubusercontent.com/assets/18460472/19269741/8b4c5b3e-8fbc-11e6-926d-a14669bc65cd.png)
