### ISSUE TITLE
File and image upload field

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#19]
![fileupload](https://cloud.githubusercontent.com/assets/3010324/19263359/3bda6e1c-8f9c-11e6-938e-2d9a6c49aaaf.png)
Example of file upload when creating or editing content. 
![imageupload](https://cloud.githubusercontent.com/assets/3010324/19263361/41f1bf8a-8f9c-11e6-8c33-b90275604464.png)
![imageuploadwithdefaultvalue](https://cloud.githubusercontent.com/assets/3010324/19263362/42052e76-8f9c-11e6-8aee-91b333f3161c.png)
Examples with image upload. Second example has image already set up in configuration as the default value

**Comment by NenadSC** [comment]
DONE

![image](https://cloud.githubusercontent.com/assets/18460472/19300247/93b1fb56-9059-11e6-9afb-90d1d7fb660d.png)
