### ISSUE TITLE
Create default / standard artboards

### ISSUE THREAD

**Issue by adrianmahlstein** [actoteam/sketch-drupal-theme-seven#2]

**Comment by NenadSC** [comment]
DONE

Created default artboards (layout for new pages). I did research decided to include most compatible version of 12 column grid, now we have included 4 layouts based on bootstrap grid, extra large and large desktop (predefined with 12 columns for screens from 980-1200+ pixels), one layout for tablet devices (8 columns) and one for mobile devices (4 columns).

![image](https://cloud.githubusercontent.com/assets/18460472/19261934/831b2ae4-8f94-11e6-9e50-8b628f6cf250.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261935/8716fbfa-8f94-11e6-8711-d82c924645af.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261937/8aa1f2a2-8f94-11e6-8a30-3dae140d0ba0.png)

![image](https://cloud.githubusercontent.com/assets/18460472/19261943/8e35eec8-8f94-11e6-8159-a2df9abc9647.png)
