### ISSUE TITLE
Date and timestamp field

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#20]
![dateandtimestamp](https://cloud.githubusercontent.com/assets/3010324/19264555/7ac3aee0-8fa1-11e6-83b4-34d434a05fcf.png)
Date and timestamp fields in the content editing/creation

**Comment by NenadSC** [comment]
DONE

![image](https://cloud.githubusercontent.com/assets/18460472/19378604/c420ed5c-91ed-11e6-86c6-ba399bbcfaa1.png)
