### ISSUE TITLE
Paragraph element

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#21]
![paragraphs](https://cloud.githubusercontent.com/assets/3010324/19264646/e1c8262a-8fa1-11e6-9f32-cf83f44891bb.png)
Add a paragraph element when creating content. Create this element as one symbol.

**Comment by NenadSC** [comment]
DONE

![image](https://cloud.githubusercontent.com/assets/18460472/19378899/85c523c8-91ef-11e6-9a53-c4706c1aaa14.png)
