### ISSUE TITLE
Admin bar with Translate option

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#22]
In case the website is multilingual there is a translate option in the admin bar. 
We need both version that is currently in Sketch (without translate) and one with the translate. 

![adminbar with translation](https://cloud.githubusercontent.com/assets/3010324/19269392/93cb929a-8fba-11e6-8bb8-8d4c056a29e2.png)

**Comment by NenadSC** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/18460472/19427766/44390542-9446-11e6-9edf-3f0175c70d5c.png)
