### ISSUE TITLE
Header title bar

### ISSUE THREAD

**Issue by NemanjaTck** [actoteam/sketch-drupal-theme-seven#23]
![headertitle](https://cloud.githubusercontent.com/assets/3010324/19272656/a06fb0da-8fc9-11e6-958a-6a1bc699611a.png)
Simple but missing. Header title (Create Article) with the star symbol missing from the elements.

**Comment by NenadSC** [comment]
DONE

![image](https://cloud.githubusercontent.com/assets/18460472/19299619/c4b364be-9055-11e6-9008-06540e55f621.png)
