### ISSUE TITLE
Symbol: Contact form

### ISSUE THREAD

**Issue by mirodietiker** [actoteam/sketch-drupal-theme-seven#4]
We need an example for a / the default contact form.

**Comment by NemanjaTck** [comment]
Providing screenshot of the contact form. All elements of the form should be grouped as one symbol.
![contactform](https://cloud.githubusercontent.com/assets/3010324/19241686/0b5167a0-8f10-11e6-80a5-b06f6d184ed2.png)

**Comment by NenadSC** [comment]
DONE

![image](https://cloud.githubusercontent.com/assets/18460472/19379129/d0a7ad2e-91f0-11e6-8dba-bca896aaf4c9.png)
